BINGPROJECTS/BINGPROJECT

Project_BING/src/main/java/com/bing/community/config/SwaggerConfig.java, Project_BING/src/main/java/com/bing/community/controller/BoardRestController.java, Project_BING/src/main/java/com/bing/community/controller/FavoriteRestController.java, Project_BING/src/main/java/com/bing/community/model/dto/Board.java, Project_BING/src/main/java/com/bing/community/model/dto/Community.java, Project_BING/src/main/java/com/bing/community/model/dto/Favorite.java, Project_BING/src/main/java/com/bing/community/model/dto/Location.java, Project_BING/src/main/java/com/bing/community/model/dto/Reply.java, Project_BING/src/main/java/com/bing/community/model/dto/User.java, Project_BING/src/main/resources/mappers/boardMapper.xml, Project_BING/src/main/resources/mappers/locationMapper.xml, Project_BING/src/main/resources/mappers/replyMapper.xml, bingproject_sql.sql
=> db수정, BoardRestController작성

Project_BING_VUE/src/views/MyPageView.vue
=> 뷰 store 오류 수정

Project_BING/src/main/java/com/bing/community/controller/FavoriteBoardRestController.java, Project_BING/src/main/resources/mappers/favoriteBoardMapper.xml, bingproject_sql.sql
=> 장소 찜 조회, 등록, 삭제 정상 동작 확인

Project_BING_VUE/src/components/board/BoardDetail.vue, Project_BING_VUE/src/router/index.js, Project_BING_VUE/src/views/BoardView.vue, Project_BING_VUE/src/views/CommunityView.vue
=> 게시판 - 게시글 리스트 - 게시글 상세 연결

Project_BING/src/main/java/com/bing/community/controller/ReplyRestController.java, Project_BING/src/main/java/com/bing/community/model/dao/ReplyDao.java, Project_BING/src/main/java/com/bing/community/model/dto/Reply.java, Project_BING/src/main/java/com/bing/community/model/service/ReplyService.java, Project_BING/src/main/java/com/bing/community/model/service/ReplyServiceImpl.java, Project_BING/src/main/resources/mappers/replyMapper.xml, Project_BING_VUE/src/components/board/BoardDetail.vue, Project_BING_VUE/src/router/index.js, Project_BING_VUE/src/stores/replyStore.js, Project_BING_VUE/src/views/BoardView.vue, Project_BING_VUE/src/views/CommunityView.vue, Project_BING_VUE/src/views/MyPageView.vue, bingproject_sql.sql
=> 게시글 - 댓글 연결

Project_BING/src/main/java/com/bing/community/controller/MyPageRestController.java, Project_BING/src/main/java/com/bing/community/controller/UserRestController.java, Project_BING/src/main/java/com/bing/community/model/dao/UserDao.java, Project_BING/src/main/java/com/bing/community/model/service/UserService.java, Project_BING/src/main/java/com/bing/community/model/service/UserServiceImpl.java, Project_BING/src/main/resources/mappers/userMapper.xml, Project_BING_VUE/src/components/commons/TheHeader.vue, Project_BING_VUE/src/components/myPage/MyBoards.vue, Project_BING_VUE/src/components/myPage/MyFavorite.vue, Project_BING_VUE/src/components/myPage/MyInfo.vue, Project_BING_VUE/src/router/index.js, Project_BING_VUE/src/stores/myPageStore.js, Project_BING_VUE/src/stores/userStore.js, Project_BING_VUE/src/views/MyPageView.vue, bingproject_sql.sql
=> 마이페이지 정보 연결 - 찜 장소 제외

Project_BING_VUE/src/App.vue, Project_BING_VUE/src/assets/main.css, Project_BING_VUE/src/components/board/BoardDetail.vue, Project_BING_VUE/src/components/board/BoardWriteForm.vue, Project_BING_VUE/src/components/board/BoardWriteMap.vue, Project_BING_VUE/src/components/commons/TheHeader.vue, Project_BING_VUE/src/components/commons/TheLoading.vue, Project_BING_VUE/src/stores/boardStore.js, Project_BING_VUE/src/views/BoardView.vue, Project_BING_VUE/src/views/BoardWriteView.vue, Project_BING_VUE/src/views/CommunityView.vue
글 작성 기능 - 장소추천 카테고리일 때 지도 첨부 하는중
=> 글 작성 기능 - 장소추천 카테고리일 때 지도 첨부 하는중

Project_BING_VUE/index.html, Project_BING_VUE/src/App.vue, Project_BING_VUE/src/components/commons/TheFooter.vue, Project_BING_VUE/src/components/commons/TheHeader.vue, Project_BING_VUE/src/components/commons/TheWeather.vue, Project_BING_VUE/src/views/MainView.vue
=> css 작업 합치기

Project_BING_VUE/src/components/commons/TheLoading.vue
=> 로딩 로고 색상 변경

Project_BING/src/main/java/com/bing/community/controller/ReplyRestController.java, Project_BING_VUE/src/components/board/BoardWriteForm.vue, Project_BING_VUE/src/components/board/BoardWriteMap.vue, Project_BING_VUE/src/router/index.js, Project_BING_VUE/src/views/BoardView.vue
=> 글 작성 - 지도 창 닫기

Project_BING/src/main/java/com/bing/community/controller/BoardRestController.java, Project_BING_VUE/src/components/board/BoardWriteForm.vue, Project_BING_VUE/src/components/board/BoardWriteMap.vue, Project_BING_VUE/src/stores/boardStore.js, Project_BING_VUE/src/stores/userStore.js
=> 게시글 등록, 회원가입 기능 구현

Project_BING/src/main/java/com/bing/community/controller/LocationRestController.java, Project_BING_VUE/src/components/board/BoardWriteForm.vue, Project_BING_VUE/src/components/commons/TheHeader.vue, Project_BING_VUE/src/stores/boardStore.js, Project_BING_VUE/src/stores/locationStore.js, Project_BING_VUE/src/views/CommunityView.vue
=> 커뮤니티 페이지 css

Project_BING_VUE/src/components/account/LoginForm.vue, Project_BING_VUE/src/components/board/BoardWriteForm.vue, Project_BING_VUE/src/stores/userStore.js, Project_BING_VUE/src/views/BoardView.vue, Project_BING_VUE/src/views/BoardWriteView.vue, Project_BING_VUE/src/views/CommunityView.vue
로그인 모달 대충, header 맞춰서 페이지 마진 설정
=> 로그인 모달 대충, header 맞춰서 페이지 마진 설정

Project_BING/src/main/java/com/bing/community/model/dto/Follow.java, Project_BING/src/main/resources/mappers/followMapper.xml, Project_BING_VUE/src/components/myPage/MyInfo.vue, Project_BING_VUE/src/components/myPage/include/MyFollow.vue, Project_BING_VUE/src/components/myPage/include/MyFollowItem.vue, Project_BING_VUE/src/stores/userStore.js
=> 팔로우 목록 작업 진행중

Project_BING_VUE/src/components/myPage/MyInfo.vue, Project_BING_VUE/src/components/myPage/include/MyFollow.vue
=> 팔로우 목록 버그 수정

Project_BING/src/main/java/com/bing/community/controller/LocationRestController.java, Project_BING/src/main/java/com/bing/community/model/dto/Location.java, Project_BING/src/main/resources/mappers/locationMapper.xml, Project_BING_VUE/src/components/board/BoardWriteMap.vue, Project_BING_VUE/src/stores/locationStore.js, bingproject_sql.sql
=> 지도 위경도 받아오게 수정

Project_BING/src/main/java/com/bing/community/controller/BoardRestController.java, Project_BING/src/main/java/com/bing/community/model/service/BoardService.java, Project_BING/src/main/java/com/bing/community/model/service/BoardServiceImpl.java, Project_BING/src/main/resources/mappers/boardMapper.xml, Project_BING_VUE/src/components/board/BoardDetail.vue, Project_BING_VUE/src/components/board/BoardListItem.vue, Project_BING_VUE/src/components/board/BoardModify.vue, Project_BING_VUE/src/components/commons/TheHeader.vue, Project_BING_VUE/src/components/myPage/MyBoards.vue, Project_BING_VUE/src/router/index.js, Project_BING_VUE/src/stores/boardStore.js, Project_BING_VUE/src/stores/userStore.js
[게시글 조회수 증가 수정](https://github.com/BINGPROJECTS/BINGPROJECT/commit/d71a80dbf9922c02380c74edff7c519274dc79e5)
=> 게시글 조회수 증가 수정

Project_BING/src/main/resources/mappers/favoriteBoardMapper.xml, Project_BING_VUE/src/components/board/BoardDetail.vue, Project_BING_VUE/src/components/board/BoardListItem.vue, Project_BING_VUE/src/components/myPage/MyBoards.vue, Project_BING_VUE/src/stores/favStore.js, Project_BING_VUE/src/stores/userStore.js
=> 로그인 시에만 찜 가능

Project_BING_VUE/index.html, Project_BING_VUE/src/components/board/BoardDetail.vue, Project_BING_VUE/src/components/board/include/BoardDetailMap.vue, Project_BING_VUE/src/stores/favStore.js, Project_BING_VUE/src/views/BoardView.vue
=> 게시물 내 지도 정보 잘못 가져오는 버그 수정

Project_BING_VUE/src/components/board/include/BoardDetailMap.vue
=> 방금 작성된 장소 추천 게시글 불러오기 버그 수정

Project_BING_VUE/src/components/board/BoardDetail.vue, Project_BING_VUE/src/stores/boardStore.js
게시글 이전/다음 버튼 눌렀을 때 로그인유저 좋아요 상태 갱신
=> 게시글 이전/다음 버튼 눌렀을 때 로그인유저 좋아요 상태 갱신

Project_BING_VUE/src/views/MainView.vue
=> 글작성 하러가는 중
